### ISSUE TITLE
запуск в аудитории

### ISSUE THREAD

**Issue by kinnder** [kinnder/warehouseSimulator#1]
Traceback (most recent call last):
  File "D:\eclipse_workspace\warehouseSimulator\warehouseSimulator.py", line 40, in <module>
    class WebServiceHTTPRequestHandler(BaseHTTPRequestHandler):
  File "D:\eclipse_workspace\warehouseSimulator\warehouseSimulator.py", line 145, in WebServiceHTTPRequestHandler
    def _get_parameter(self, parameters: dict[str, list[str]], parameter_name: str) -> int:
TypeError: 'type' object is not subscriptable

**Comment by kinnder** [comment]
os: windows7, python: 3.8.10
